"use client";

import { useMemo, useState } from "react";
import { Clock3, Plus, Trash2 } from "lucide-react";
import type { Availability, AvailabilityInput } from "../types";
import { validateAvailability } from "../validations";
import StatusBadge from "./StatusBadge";

export default function AvailabilityCalendar({ slots, onChange }: { slots: Availability[]; onChange: (slots: AvailabilityInput[]) => Promise<void> }) {
  const [items, setItems] = useState(slots);
  const [form, setForm] = useState<AvailabilityInput>({ date: "2026-08-24", startTime: "09:00", endTime: "12:00", status: "Available" });
  const [error, setError] = useState("");
  const grouped = useMemo(() => Object.entries(Object.groupBy(items, (slot) => slot.date)).sort(([a], [b]) => a.localeCompare(b)), [items]);
  async function commit(next: Availability[]) { setItems(next); await onChange(next.map((slot) => ({ date: slot.date, startTime: slot.startTime, endTime: slot.endTime, status: slot.status }))); }
  async function add(event: React.FormEvent) { event.preventDefault(); const validation = validateAvailability(form); if (validation) { setError(validation); return; } setError(""); await commit([...items, { ...form, id: `local-${Date.now()}` }]); }
  return <div className="grid gap-6 xl:grid-cols-[1fr_340px]"><section className="rounded-lg border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-bold">Weekly availability</h2><p className="mt-1 text-xs text-slate-500">Your configured clinic hours for the current week</p></div><div className="divide-y divide-slate-100">{grouped.map(([date, daySlots]) => <div key={date} className="grid gap-3 px-5 py-4 sm:grid-cols-[150px_1fr]"><div><p className="text-sm font-semibold">{new Date(`${date}T00:00:00`).toLocaleDateString("en-US", { weekday: "long" })}</p><p className="text-xs text-slate-500">{new Date(`${date}T00:00:00`).toLocaleDateString("en-US", { month: "short", day: "numeric" })}</p></div><div className="space-y-2">{daySlots?.map((slot) => <div key={slot.id} className="flex flex-wrap items-center justify-between gap-3 rounded-md bg-slate-50 px-3 py-2"><span className="flex items-center gap-2 text-sm"><Clock3 className="h-4 w-4 text-slate-400" />{slot.startTime} - {slot.endTime}</span><div className="flex items-center gap-2"><StatusBadge status={slot.status} /><button aria-label="Remove time slot" onClick={() => void commit(items.filter((item) => item.id !== slot.id))} className="flex h-8 w-8 items-center justify-center rounded-md text-slate-400 hover:bg-rose-50 hover:text-rose-600"><Trash2 className="h-4 w-4" /></button></div></div>)}</div></div>)}</div></section>
    <form onSubmit={add} className="h-fit rounded-lg border border-slate-200 bg-white p-5 shadow-sm"><h2 className="flex items-center gap-2 font-bold"><Plus className="h-4 w-4 text-blue-600" />Add time slot</h2>{error && <p className="mt-3 text-xs text-rose-600">{error}</p>}<div className="mt-5 space-y-4"><SmallLabel text="Date"><input type="date" value={form.date} onChange={(e) => setForm({ ...form, date: e.target.value })} /></SmallLabel><div className="grid grid-cols-2 gap-3"><SmallLabel text="Start time"><input type="time" value={form.startTime} onChange={(e) => setForm({ ...form, startTime: e.target.value })} /></SmallLabel><SmallLabel text="End time"><input type="time" value={form.endTime} onChange={(e) => setForm({ ...form, endTime: e.target.value })} /></SmallLabel></div><SmallLabel text="Status"><select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value as AvailabilityInput["status"] })}><option>Available</option><option>Unavailable</option></select></SmallLabel><button className="h-11 w-full rounded-md bg-blue-600 text-sm font-semibold text-white hover:bg-blue-700">Add availability</button></div></form></div>;
}
function SmallLabel({ text, children }: { text: string; children: React.ReactElement<{ className?: string }> }) { return <label className="block text-xs font-semibold text-slate-600">{text}<span className="mt-1.5 block">{children}</span></label>; }
