import type { OperationalLaboratoryOperationsDto, OperationalLabTurnaroundDto } from "@/types/analytics";

function StatusList({ title, entries }: { title: string; entries: { status: string; count: number }[] }) {
  return <div><h3 className="mb-2 text-xs font-semibold text-slate-500">{title}</h3><div className="space-y-2">{entries.map((entry) => <div key={entry.status} className="flex items-center justify-between gap-3 text-xs"><span className="text-slate-500">{entry.status}</span><strong className="text-slate-800">{entry.count.toLocaleString()}</strong></div>)}</div></div>;
}

export default function OperationalLaboratorySummary({ operations, turnaround }: { operations: OperationalLaboratoryOperationsDto; turnaround: OperationalLabTurnaroundDto }) {
  return <div className="space-y-5"><div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><div className="rounded-xl border border-slate-100 bg-slate-50 p-3"><p className="text-[11px] text-slate-400">Total orders</p><p className="mt-1 text-lg font-bold text-slate-800">{operations.totalOrders.toLocaleString()}</p></div><div className="rounded-xl border border-slate-100 bg-slate-50 p-3"><p className="text-[11px] text-slate-400">Completed</p><p className="mt-1 text-lg font-bold text-slate-800">{operations.completedOrders.toLocaleString()}</p></div><div className="rounded-xl border border-slate-100 bg-slate-50 p-3"><p className="text-[11px] text-slate-400">Completion rate</p><p className="mt-1 text-lg font-bold text-teal-600">{operations.completionRate}%</p></div><div className="rounded-xl border border-slate-100 bg-slate-50 p-3"><p className="text-[11px] text-slate-400">Avg turnaround</p><p className="mt-1 text-lg font-bold text-slate-800">{turnaround.averageHours} hrs</p></div></div><div className="grid grid-cols-1 gap-5 sm:grid-cols-2"><StatusList title="Lab order status" entries={operations.orderStatus} /><StatusList title="Lab sample status" entries={operations.sampleStatus} /></div><p className="text-xs text-slate-400">{turnaround.definition} {turnaround.excludedRecords.toLocaleString()} records excluded from turnaround coverage.</p></div>;
}
