"use client";
import { useCallback } from "react";
import { Banknote, CircleDollarSign, Clock3, TrendingUp } from "lucide-react";
import DoctorStatsCard from "@/features/doctor/components/DoctorStatsCard";
import EarningsChart from "@/features/doctor/components/EarningsChart";
import LoadingState from "@/features/doctor/components/LoadingState";
import PageHeader from "@/features/doctor/components/PageHeader";
import StatusBadge from "@/features/doctor/components/StatusBadge";
import { useDoctorData } from "@/features/doctor/hooks/useDoctorData";
import { getEarnings } from "@/features/doctor/services/doctorService";
export default function DoctorEarningsPage() { const loader = useCallback(() => getEarnings(), []); const { data, loading, error } = useDoctorData(loader); if (loading) return <LoadingState />; if (error || !data) return <p className="text-sm text-rose-600">{error}</p>; return <><PageHeader eyebrow="Finance" title="Earnings dashboard" description="Track consultation revenue and recent patient payments." /><section className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4"><DoctorStatsCard label="Total earnings" value={`LKR ${(data.totalEarnings / 1000000).toFixed(2)}M`} detail="All-time consultation revenue" icon={CircleDollarSign} /><DoctorStatsCard label="This month" value={`LKR ${(data.monthlyEarnings / 1000).toFixed(1)}K`} detail="12.4% above last month" icon={TrendingUp} tone="blue" /><DoctorStatsCard label="Consultation income" value={`LKR ${(data.consultationIncome / 1000).toFixed(1)}K`} detail="31 completed consultations" icon={Banknote} tone="amber" /><DoctorStatsCard label="Pending" value={`LKR ${(data.pendingAmount / 1000).toFixed(1)}K`} detail="Awaiting payment settlement" icon={Clock3} tone="rose" /></section><section className="mt-6 rounded-lg border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div><h2 className="font-bold">Revenue overview</h2><p className="mt-1 text-xs text-slate-500">Monthly consultation revenue for the last six months</p></div><div className="mt-5"><EarningsChart data={data.revenue} /></div></section><section className="mt-6 overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-bold">Payment history</h2><p className="mt-1 text-xs text-slate-500">Recent consultation transactions</p></div><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="px-5 py-3 font-semibold">Reference</th><th className="px-5 py-3 font-semibold">Patient</th><th className="px-5 py-3 font-semibold">Date</th><th className="px-5 py-3 font-semibold">Service</th><th className="px-5 py-3 font-semibold">Amount</th><th className="px-5 py-3 font-semibold">Status</th></tr></thead><tbody className="divide-y divide-slate-100">{data.payments.map((payment) => <tr key={payment.id}><td className="px-5 py-4 font-mono text-xs text-slate-500">{payment.id}</td><td className="px-5 py-4 font-semibold">{payment.patientName}</td><td className="px-5 py-4 text-slate-600">{payment.date}</td><td className="px-5 py-4 text-slate-600">{payment.service}</td><td className="px-5 py-4 font-semibold">LKR {payment.amount.toLocaleString()}</td><td className="px-5 py-4"><StatusBadge status={payment.status} /></td></tr>)}</tbody></table></div></section></>; }
