package lk.gamage.backend.healthbridgebackend.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;
import java.util.List;

/**
 * Stores the clinical outcome of a telemedicine call: doctor notes,
 * AI-generated summary, and follow-up flags. One-to-one with a
 * TelemedicineSession once that session completes.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Document(collection = "consultation_sessions")
public class ConsultationSession {

    @Id
    private String id;

    @Indexed(unique = true)
    private String telemedicineSessionId;

    private String appointmentId;

    private String patientId;

    private String doctorId;

    /** Free-text notes entered by the doctor during/after the call */
    private String doctorNotes;

    /** Summary generated by the AI summarization service from the transcript */
    private String aiGeneratedSummary;

    private AiSummaryStatus aiSummaryStatus;

    private List<String> keySymptomsDiscussed;

    private List<String> followUpActions;

    private boolean followUpRequired;

    private LocalDateTime followUpDate;

    private RecordingMetadata recordingMetadata;

    @CreatedDate
    private LocalDateTime createdAt;

    public enum AiSummaryStatus {
        NOT_REQUESTED,
        PENDING,
        COMPLETED,
        FAILED
    }
}
