import type { ReportCategory, ReportFormat, ReportPeriod } from "@/types/analytics";

type GenerateReportPanelProps = { reportType: ReportCategory; period: ReportPeriod; department: string; format: ReportFormat; isGenerating: boolean; onReportTypeChange: (value: ReportCategory) => void; onPeriodChange: (value: ReportPeriod) => void; onDepartmentChange: (value: string) => void; onFormatChange: (value: ReportFormat) => void; onGenerate: () => void; reportTypes: { label: string; value: ReportCategory }[]; periods: ReportPeriod[]; departments: string[] };

const fieldClass = "mt-1.5 w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm text-slate-700 outline-none transition focus:border-blue-400 focus:ring-2 focus:ring-blue-100";

export default function GenerateReportPanel({ reportType, period, department, format, isGenerating, onReportTypeChange, onPeriodChange, onDepartmentChange, onFormatChange, onGenerate, reportTypes, periods, departments }: GenerateReportPanelProps) {
  return <div className="space-y-4"><div className="grid grid-cols-1 gap-4 sm:grid-cols-2"><label className="text-xs font-semibold text-slate-600">Report Type<select value={reportType} onChange={(event) => onReportTypeChange(event.target.value as ReportCategory)} className={fieldClass}>{reportTypes.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label><label className="text-xs font-semibold text-slate-600">Period<select value={period} onChange={(event) => onPeriodChange(event.target.value as ReportPeriod)} className={fieldClass}>{periods.map((option) => <option key={option} value={option}>{option}</option>)}</select></label><label className="text-xs font-semibold text-slate-600">Department<select value={department} onChange={(event) => onDepartmentChange(event.target.value)} className={fieldClass}>{departments.map((option) => <option key={option} value={option}>{option}</option>)}</select></label><fieldset><legend className="text-xs font-semibold text-slate-600">Format</legend><div className="mt-1.5 flex gap-2">{(["PDF", "Excel"] as ReportFormat[]).map((option) => <label key={option} className={`flex flex-1 cursor-pointer items-center justify-center rounded-xl border px-3 py-2.5 text-sm font-semibold transition ${format === option ? "border-blue-200 bg-blue-50 text-blue-700" : "border-slate-200 text-slate-500 hover:border-blue-100"}`}><input type="radio" name="report-format" value={option} checked={format === option} onChange={() => onFormatChange(option)} className="sr-only" />{option}</label>)}</div></fieldset></div><div className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-blue-50/70 p-3"><p className="text-xs text-blue-700">PDF and Excel are frontend selections. Export integration will be enabled with the reporting backend.</p><button type="button" onClick={onGenerate} disabled={isGenerating} className="rounded-xl bg-blue-600 px-4 py-2.5 text-xs font-semibold text-white shadow-sm transition hover:bg-blue-700 disabled:cursor-wait disabled:opacity-60">{isGenerating ? "Generating..." : "Generate Report"}</button></div></div>;
}
